version: "3.5"

services:
  api01: &api
    image: brenonaraujo/rinhabackend-q12024:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DATABASE_URL=postgres://admin:123@db:5432/rinha
      - INSTANCE_ID=api01
    ports:
      - "33910:33888"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"
    
  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DATABASE_URL=postgres://admin:123@db:5432/rinha
      - INSTANCE_ID=api02
    ports:
      - "33911:33888"
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "55735:5432"
    volumes:
      - ./infra/database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=1200 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "240MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
