version: "3.5"

services:
  api01:
    image: brenonaraujo/rinhabackend-q12024:latest
    restart: always
    environment:
      - DB_HOSTNAME=localhost
      - DATABASE_URL=postgres://admin:123@localhost:55735/rinha
      - GIN_MODE=release
      - HTTP_PORT=:33910
    depends_on:
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"
    
  api02:
    image: brenonaraujo/rinhabackend-q12024:latest
    restart: always
    environment:
      - DB_HOSTNAME=localhost
      - DATABASE_URL=postgres://admin:123@localhost:55735/rinha
      - GIN_MODE=release
      - HTTP_PORT=:33911
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -p 55735 -c checkpoint_timeout=600 -c max_wal_size=4096 -c max_connections=600 -c shared_buffers=140MB
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "330MB"
